declare less, integer
store true, less
declare more, integer
store false, more
declare a, real
store 1.5, a
declare b, real
store 2.0, b
declare c, real
store 2.5, c
declare d, real
store 5.0, d
declare x, real
store 22.4, x
declare f, character
store 'a', f
declare g, integer
declare j, integer
store 2, j
declare m, integer
store 92, m
declare &tempi1, integer
low a, b, &tempi1
